### PR TITLE
Bump aeson dep

### PR DESCRIPTION
**Pull request by k-bx**

### CODE REVIEW

**Comment by k-bx** [comment]
Would be nice to make a release before https://www.stackage.org/blog/2018/06/upcoming-lts-12-ghc-8-4-3

**Comment by MichaelXavier** [comment]
Thanks! Test failure looks unrelated to you. I'll get it resolved and update here when the package is released.

**Comment by bergmark** [comment]
Note that aeson 1.4.0.0 is out

**Comment by MichaelXavier** [comment]
I just tore the upper bound off yaml and aeson. Released at `ua-parser-0.7.5.0`

**Pull request merged**
