### PR TITLE
Getting uap-haskell in line with uap-core

### PR DESCRIPTION
**Pull request by bitemyapp**
Couple spooky tests (Other & Android Donut) still breaking, but this is still vastly improved over what we were doing before.

/cc @ozataman

### CODE REVIEW

**Comment by bitemyapp** [comment]
@ozataman is this PR suitable?

**Comment by ozataman** [comment]
Apologies Chris, havent had a chance to review due to travel. Will get back to you as soon as I get the chance.

**Comment by bitemyapp** [comment]
@ozataman all good, thank you for letting me know :) :+1:

**Comment by MichaelXavier** [comment]
I've been tasked with getting this project cleaned up and tracking uap-core. This code looks good to me. Since this project is on someone else's org and there's some further cleanup to do, I'm going to ahead and merge this to a cleanup branch off master. Thanks @bitemyapp!

**Comment by MichaelXavier** [comment]
Merged to uap-core-update.

**Pull request closed without merging**
